import { Category } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', name: 'Food & Drinks', icon: 'Utensils', color: '#FFB7B2' }, // Pastel Red
  { id: '2', name: 'Transport', icon: 'Car', color: '#B2E2F2' }, // Pastel Blue
  { id: '3', name: 'Shopping', icon: 'ShoppingBag', color: '#FDFD96' }, // Pastel Yellow
  { id: '4', name: 'Entertainment', icon: 'Film', color: '#B2B2B2' }, // Muted Gray
  { id: '5', name: 'Health', icon: 'Heart', color: '#FF6961' }, // Muted Red
  { id: '6', name: 'Salary', icon: 'Wallet', color: '#77DD77' }, // Pastel Green
  { id: '7', name: 'Housing', icon: 'Home', color: '#CFCFC4' }, // Muted Earth
  { id: '8', name: 'Education', icon: 'GraduationCap', color: '#AEC6CF' }, // Muted Blue
];

export const CURRENCIES = [
  { code: 'GHS', symbol: 'GH₵' },
  { code: 'USD', symbol: '$' },
  { code: 'EUR', symbol: '€' },
  { code: 'GBP', symbol: '£' },
  { code: 'JPY', symbol: '¥' },
  { code: 'AUD', symbol: 'A$' },
  { code: 'CAD', symbol: 'C$' },
  { code: 'CHF', symbol: 'Fr' },
  { code: 'CNY', symbol: '¥' },
  { code: 'HKD', symbol: 'HK$' },
  { code: 'NZD', symbol: 'NZ$' },
  { code: 'SEK', symbol: 'kr' },
  { code: 'KRW', symbol: '₩' },
  { code: 'SGD', symbol: 'S$' },
  { code: 'NOK', symbol: 'kr' },
  { code: 'MXN', symbol: '$' },
  { code: 'INR', symbol: '₹' },
  { code: 'RUB', symbol: '₽' },
  { code: 'ZAR', symbol: 'R' },
  { code: 'TRY', symbol: '₺' },
  { code: 'BRL', symbol: 'R$' },
  { code: 'TWD', symbol: 'NT$' },
  { code: 'DKK', symbol: 'kr' },
  { code: 'PLN', symbol: 'zł' },
  { code: 'THB', symbol: '฿' },
  { code: 'IDR', symbol: 'Rp' },
  { code: 'HUF', symbol: 'Ft' },
  { code: 'CZK', symbol: 'Kč' },
  { code: 'ILS', symbol: '₪' },
  { code: 'CLP', symbol: '$' },
  { code: 'PHP', symbol: '₱' },
  { code: 'AED', symbol: 'د.إ' },
  { code: 'COP', symbol: '$' },
  { code: 'SAR', symbol: '﷼' },
  { code: 'MYR', symbol: 'RM' },
  { code: 'RON', symbol: 'lei' },
  { code: 'NGN', symbol: '₦' },
  { code: 'ARS', symbol: '$' },
  { code: 'EGP', symbol: 'E£' },
  { code: 'VND', symbol: '₫' },
  { code: 'UAH', symbol: '₴' },
  { code: 'KWD', symbol: 'KD' },
  { code: 'QAR', symbol: 'QR' },
  { code: 'PKR', symbol: '₨' },
  { code: 'BWP', symbol: 'P' },
  { code: 'KES', symbol: 'KSh' },
  { code: 'UGX', symbol: 'USh' },
  { code: 'TZS', symbol: 'TSh' },
  { code: 'ZMW', symbol: 'ZK' },
  { code: 'MAD', symbol: 'DH' },
  { code: 'DOP', symbol: 'RD$' },
  { code: 'CUP', symbol: '$' },
  { code: 'CRC', symbol: '₡' },
  { code: 'PEN', symbol: 'S/' },
  { code: 'UYU', symbol: '$U' },
  { code: 'PYG', symbol: '₲' },
  { code: 'BOB', symbol: 'Bs.' },
  { code: 'KZT', symbol: '₸' },
  { code: 'UZS', symbol: 'лв' },
  { code: 'LKR', symbol: 'Rs' },
  { code: 'NPR', symbol: 'Rs' },
  { code: 'MMK', symbol: 'K' },
  { code: 'KHR', symbol: '៛' },
  { code: 'LAK', symbol: '₭' },
  { code: 'MNT', symbol: '₮' },
  { code: 'HNL', symbol: 'L' },
  { code: 'NIO', symbol: 'C$' },
  { code: 'GTQ', symbol: 'Q' },
  { code: 'PAB', symbol: 'B/.' },
  { code: 'JMD', symbol: 'J$' },
  { code: 'TTD', symbol: 'TT$' },
  { code: 'XCD', symbol: '$' },
  { code: 'BBD', symbol: '$' },
  { code: 'FJD', symbol: '$' },
  { code: 'PGK', symbol: 'K' },
  { code: 'XPF', symbol: '₣' },
  { code: 'TOP', symbol: 'T$' },
  { code: 'WST', symbol: 'T' },
  { code: 'VUV', symbol: 'Vt' },
  { code: 'SBD', symbol: '$' },
  { code: 'GMD', symbol: 'D' },
  { code: 'SLE', symbol: 'Le' },
  { code: 'LSL', symbol: 'L' },
  { code: 'SZL', symbol: 'L' },
  { code: 'NAD', symbol: '$' },
];
